/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package imh.tp3;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Stroke;
import java.awt.geom.AffineTransform;
import java.time.LocalDateTime;

/**
 *
 * @author logan
 */
public class Horloge extends javax.swing.JPanel {

    /**
     * Creates new form Horloge
     */
    public Horloge() {
        initComponents();
        
        // On initialise les timers
        javax.swing.Timer timer = new javax.swing.Timer(1000, (e) -> {
            time = LocalDateTime.now();
            this.repaint();
        });
        timer.start();
        
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        Graphics2D g2d = (Graphics2D) g;
        // Anti-aliasing
        g2d.setRenderingHint(
        java.awt.RenderingHints.KEY_ANTIALIASING,
        java.awt.RenderingHints.VALUE_ANTIALIAS_ON
        );        
        int w = getWidth();
        int h = getHeight();
        
        int centerX = w/2;
        int centerY = h/2;
        
        Point center = new Point(centerX,centerY);
        
        // On déssine l'horloge initial sans les composants
        g2d.setColor(Color.GRAY);
        g2d.fillOval(0,0, w, h);
        
        // On dessine les points sur chaque heures
        g2d.setColor(Color.BLACK);
        for (int i = 0; i < 12; i++) {
            Point point = new Point(w/2, 10);
            Point rotatedPoint = rotatePoint(point, center, getHourRotation(i));
            g2d.fillOval((int)rotatedPoint.getX()-2, (int)rotatedPoint.getY()-2, 4, 4);
            
        }
        
        int sec = time.getSecond();
        int min = time.getMinute();
        int hour = time.getHour();

        // On définit les angles
        int secAngle = getSecondsRotation(sec);
        int minAngle = getMinuteRotation(min);
        int hourAngle = getHourRotation(hour) + (min / 2);
        
        // On définit les points de base
        Point secBase = new Point(centerX, (int)(centerY*0.1));
        Point minBase = new Point(centerX, (int)(centerY*0.3));
        Point hourBase = new Point(centerX, (int)(centerY*0.5));
        
        // On définit les rotations
        Point secPoint = rotatePoint(secBase,center,secAngle);
        Point minPoint = rotatePoint(minBase,center,minAngle);
        Point hourPoint = rotatePoint(hourBase,center,hourAngle);

        // On dessine les traits pour:
        // Les secondes (épaisseur = 2px)
        g2d.setColor(Color.RED);
        g2d.setStroke(new BasicStroke(2));
        g2d.drawLine(centerX, centerY, secPoint.x, secPoint.y);
        // Les minutes (épaisseur = 3px)
        g2d.setColor(Color.BLACK);
        g2d.setStroke(new BasicStroke(3));
        g2d.drawLine(centerX, centerY, minPoint.x, minPoint.y);
        // Les heures (épaisseur = 4px)
        g2d.setStroke(new BasicStroke(4));
        g2d.drawLine(centerX, centerY, hourPoint.x, hourPoint.y);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //retourne le degré de rotation d'une seconde sur l'horloge
    private int getSecondsRotation(int seconds) {
        return (360/60) * seconds;
    }
    //retourn le degré de rotation d'une minute sur l'horloge
    private int getMinuteRotation(int minutes) {
        return (360/60) * minutes;
    }
    //retourne le degré de rotation d'une heure sur l'horloge
    private int getHourRotation(int hours) {
        return (360/12) * hours;
    }
    // retourne un point qui a été tourné autour du centre selon le degré
    private Point rotatePoint(Point point, Point center, int degree) {
        AffineTransform rotation = new AffineTransform();
        double angleInRadians = (degree * Math.PI / 180);
        rotation.rotate(angleInRadians, center.getX(), center.getY());
        Point result = new Point();
        rotation.transform(point, result);
        return result;
    }
    

        // On définit l'heure à lire (heure actuelle)
        LocalDateTime time = LocalDateTime.now();

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
