/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm.tp1;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author logan
 */
public class exo2_gestion_impressions extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(exo2_gestion_impressions.class.getName());

    /**
     * Creates new form exo2_gestion_impressions
     */
    public exo2_gestion_impressions() {
        initComponents();
        // On init la liste en la liant à listModel
        // pour pouvoir modifier dynamiquement la liste
        jList_impress_plan.setModel(listModel);
        
        // Init des boutons
        jTextField_nom_fichier.setEnabled(false);
        
        jRadioButton_noir_blanc.setSelected(true);
        jRadioButton_couleur.setSelected(false);
        
        jButton_ajouter.setEnabled(false);
        jButton_modifier.setEnabled(false);
        jButton_supprimer.setEnabled(false);
        
        jList_impress_plan.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JP_fichier_a_imprimer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_nom_fichier = new javax.swing.JTextField();
        jButton_parcourir = new javax.swing.JButton();
        JP_option_impression = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_nb_copies = new javax.swing.JSpinner();
        jComboBox_format = new javax.swing.JComboBox<>();
        jCheckBox_recto_verso = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton_noir_blanc = new javax.swing.JRadioButton();
        jRadioButton_couleur = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_qualite_papier = new javax.swing.JComboBox<>();
        JP_impressions_plannifiees = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_supprimer = new javax.swing.JButton();
        jButton_ajouter = new javax.swing.JButton();
        jButton_modifier = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_impress_plan = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion impressions");

        JP_fichier_a_imprimer.setBorder(javax.swing.BorderFactory.createTitledBorder("Fichier à imprimer"));
        JP_fichier_a_imprimer.setName(""); // NOI18N

        jLabel1.setText("Nom du fichier:");

        jButton_parcourir.setText("Parcourir...");
        jButton_parcourir.addActionListener(this::jButton_parcourirActionPerformed);

        javax.swing.GroupLayout JP_fichier_a_imprimerLayout = new javax.swing.GroupLayout(JP_fichier_a_imprimer);
        JP_fichier_a_imprimer.setLayout(JP_fichier_a_imprimerLayout);
        JP_fichier_a_imprimerLayout.setHorizontalGroup(
            JP_fichier_a_imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_fichier_a_imprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nom_fichier, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_parcourir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_fichier_a_imprimerLayout.setVerticalGroup(
            JP_fichier_a_imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_fichier_a_imprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_fichier_a_imprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_nom_fichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_parcourir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JP_option_impression.setBorder(javax.swing.BorderFactory.createTitledBorder("Option d'impression"));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setText("Nb de copies");

        jLabel3.setText("Format");

        jSpinner_nb_copies.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner_nb_copies.setValue(1);

        jComboBox_format.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A3", "A4", "A5", "Lettre" }));

        jCheckBox_recto_verso.setText("Recto/Verso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_recto_verso)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jSpinner_nb_copies, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner_nb_copies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_format, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jCheckBox_recto_verso)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        buttonGroup1.add(jRadioButton_noir_blanc);
        jRadioButton_noir_blanc.setText("Noir et Blanc");

        buttonGroup1.add(jRadioButton_couleur);
        jRadioButton_couleur.setText("Couleur");

        jLabel4.setText("<html><body>Qualité <br> du papier </body></html>");

        jComboBox_qualite_papier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economique", "Régulier" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton_noir_blanc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_couleur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_qualite_papier, 0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_noir_blanc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_couleur)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_qualite_papier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout JP_option_impressionLayout = new javax.swing.GroupLayout(JP_option_impression);
        JP_option_impression.setLayout(JP_option_impressionLayout);
        JP_option_impressionLayout.setHorizontalGroup(
            JP_option_impressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_option_impressionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JP_option_impressionLayout.setVerticalGroup(
            JP_option_impressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_option_impressionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_option_impressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        JP_impressions_plannifiees.setBorder(javax.swing.BorderFactory.createTitledBorder("Impression planifiées"));

        jButton_supprimer.setText("Supprimer");
        jButton_supprimer.addActionListener(this::jButton_supprimerActionPerformed);

        jButton_ajouter.setText("Ajouter");
        jButton_ajouter.addActionListener(this::jButton_ajouterActionPerformed);

        jButton_modifier.setText("Modifier");
        jButton_modifier.addActionListener(this::jButton_modifierActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_ajouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_modifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_supprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_ajouter, jButton_modifier, jButton_supprimer});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton_ajouter)
                    .addComponent(jButton_modifier)
                    .addComponent(jButton_supprimer))
                .addContainerGap())
        );

        jList_impress_plan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_impress_planMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_impress_plan);

        javax.swing.GroupLayout JP_impressions_plannifieesLayout = new javax.swing.GroupLayout(JP_impressions_plannifiees);
        JP_impressions_plannifiees.setLayout(JP_impressions_plannifieesLayout);
        JP_impressions_plannifieesLayout.setHorizontalGroup(
            JP_impressions_plannifieesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_impressions_plannifieesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_impressions_plannifieesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        JP_impressions_plannifieesLayout.setVerticalGroup(
            JP_impressions_plannifieesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_impressions_plannifieesLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JP_impressions_plannifiees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_option_impression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_fichier_a_imprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JP_fichier_a_imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JP_option_impression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JP_impressions_plannifiees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_parcourirActionPerformed
        // On initialise le fileChooser
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(this);        
        
        if(result == JFileChooser.APPROVE_OPTION){
            File fichierSelectionne = fc.getSelectedFile();
            // On met le path dans la textbox
            jTextField_nom_fichier.setText(fichierSelectionne.getAbsolutePath());
            // Le chemin est correcte, on peut réactiver le bouton Ajouter
            jButton_ajouter.setEnabled(true);
            jList_impress_plan.setEnabled(true);
        }
        
       
    }//GEN-LAST:event_jButton_parcourirActionPerformed

    private void jButton_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifierActionPerformed
        // TODO add your handling code here:
        int index = jList_impress_plan.getSelectedIndex();
        ImpressionFile item_selectionne = jList_impress_plan.getSelectedValue();

        // On modifie les donnée d'un item sélectionné
        item_selectionne.setNumber((int) jSpinner_nb_copies.getValue());
        item_selectionne.setFormat((String) jComboBox_format.getSelectedItem());
        item_selectionne.setDoubleSide(jCheckBox_recto_verso.isSelected());
        item_selectionne.setBlackAndWhite(jRadioButton_noir_blanc.isSelected());
        item_selectionne.setBlackAndWhite(!jRadioButton_couleur.isSelected());
        item_selectionne.setPaperQuality((String) jComboBox_qualite_papier.getSelectedItem());
        
        listModel.set(index, item_selectionne);
        
    }//GEN-LAST:event_jButton_modifierActionPerformed

    private void jButton_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ajouterActionPerformed
        // On lit le chemin dans la textBox nom du fichier 
        // On initialise le fichier avec ImpressionFile pour pouvoir ensuite le mettre dans la liste
        String fileName = jTextField_nom_fichier.getText();
        int number = (int) jSpinner_nb_copies.getValue();
        String format = (String) jComboBox_format.getSelectedItem();
        boolean rectoVerso = jCheckBox_recto_verso.isSelected();
        boolean noirBlanc = jRadioButton_noir_blanc.isSelected();
        boolean couleur = !jRadioButton_couleur.isSelected();
        String paperQuality = (String) jComboBox_qualite_papier.getSelectedItem();

        ImpressionFile imprFile = new ImpressionFile(fileName, number, format, rectoVerso, couleur, paperQuality);

        listModel.addElement(imprFile);
    }//GEN-LAST:event_jButton_ajouterActionPerformed

    private void jButton_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_supprimerActionPerformed
        // TODO add your handling code here:
        int index = jList_impress_plan.getSelectedIndex();
        
        // On supprime l'élément de la liste
        listModel.remove(index);
        // Aucun éléments de la liste n'est sélectionné
        jList_impress_plan.setSelectedIndex(-1);
        // On remet par défaut tout les paramètres
        jSpinner_nb_copies.setValue(1);
        jComboBox_format.setSelectedIndex(0);
        jCheckBox_recto_verso.setSelected(false);
        jRadioButton_noir_blanc.setSelected(true);
        jRadioButton_couleur.setSelected(false);
        jComboBox_qualite_papier.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton_supprimerActionPerformed

    private void jList_impress_planMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_impress_planMouseClicked
        boolean item_selectionne_vide = jList_impress_plan.isSelectionEmpty();
        ImpressionFile item_selectionne = jList_impress_plan.getSelectedValue();
        // Si on a bien cliqué sur un élément de la liste et pas dans une zone vide de celle-ci,
        // on rend accessible Modifier et Supprimer
        jButton_modifier.setEnabled(!item_selectionne_vide);
        jButton_supprimer.setEnabled(!item_selectionne_vide);
        
        // Quand on sélectionne un item on change les données d'impressions correspondantes
        jSpinner_nb_copies.setValue(item_selectionne.getNumber());
        jComboBox_format.setSelectedItem(item_selectionne.getFormat());
        jCheckBox_recto_verso.setSelected(item_selectionne.isDoubleSide());
        jRadioButton_noir_blanc.setSelected(item_selectionne.isBlackAndWhite());
        jRadioButton_couleur.setSelected(!item_selectionne.isBlackAndWhite());
        jComboBox_qualite_papier.setSelectedItem(item_selectionne.getPaperQuality());
    }//GEN-LAST:event_jList_impress_planMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new exo2_gestion_impressions().setVisible(true));
    }
    
    // Ajout de defaultListModel pour pouvoir modifier la liste dynamiquement
    private javax.swing.DefaultListModel<ImpressionFile> listModel = new javax.swing.DefaultListModel<>();
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_fichier_a_imprimer;
    private javax.swing.JPanel JP_impressions_plannifiees;
    private javax.swing.JPanel JP_option_impression;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_ajouter;
    private javax.swing.JButton jButton_modifier;
    private javax.swing.JButton jButton_parcourir;
    private javax.swing.JButton jButton_supprimer;
    private javax.swing.JCheckBox jCheckBox_recto_verso;
    private javax.swing.JComboBox<String> jComboBox_format;
    private javax.swing.JComboBox<String> jComboBox_qualite_papier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<ImpressionFile> jList_impress_plan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_couleur;
    private javax.swing.JRadioButton jRadioButton_noir_blanc;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_nb_copies;
    private javax.swing.JTextField jTextField_nom_fichier;
    // End of variables declaration//GEN-END:variables
}
