/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ihm.tp2.exo1.exo2;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.util.List;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author logan
 */
public class Canva extends javax.swing.JPanel {

    /**
     * Creates new form Canva
     */
    public Canva() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
       /**
        * On parcours le liste de ColorPoint et pour chaque point:
        *   - Définit la couleur sur le Graphics
        *   - Définit l'épaisseur (on oublie pas de caster g en Graphics2D)
        *   - On dessine un ovale centré sur point.x et point.y avec la taille et l'épaisseur
        */
       Graphics2D g2d = (Graphics2D) g;
       for (ColorPoint point : listColorPoints){
           int x = (int) point.getPoint().getX();
           int y = (int) point.getPoint().getY();
           Color color = point.getColor();
           int thickness = point.getThickness();
           
           g2d.setColor(color);
           // Contrairement à drawOval, là on dessine un oval rempli
           g2d.fillOval(x, y, thickness, thickness);
       }
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // Quand on fait un clic gauche, on réccupère les coordonnée de la souris
        if(SwingUtilities.isLeftMouseButton(evt)){
            // On regarde quel bouton est sélectionnée pour les couleurs et l'épaisseur
            Color color = currentColor;
            int thickness = currentThickness;
            
            // On initialise les coordonnées de la souris et colorPoint
            Point point = evt.getPoint();
            ColorPoint colorPoint = new ColorPoint(color,point,thickness);
            
            // On les stock ensuite dans la classe ColorPoint
            listColorPoints.add(colorPoint);
            
            // On oublie pas de repaint
            this.repaint();
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // Quand on fait un clic gauche, on réccupère les coordonnée de la souris
        if(SwingUtilities.isLeftMouseButton(evt)){
            // On regarde quel bouton est sélectionnée pour les couleurs et l'épaisseur
            Color color = currentColor;
            int thickness = currentThickness;
            
            Point point = evt.getPoint();
            ColorPoint colorPoint = new ColorPoint(color,point,thickness);
            
            // On les stock ensuite dans la classe ColorPoint
            listColorPoints.add(colorPoint);
            
            // On oublie pas de repaint
            this.repaint();
        }
    }//GEN-LAST:event_formMouseDragged


    public void setCurrentColor(Color color){
        currentColor = color;
    }
    
    public void setCurrentThickness(int thickness){
        currentThickness = thickness;
    }
    
    
    // On initialise une liste de ColorPoint
    private Color currentColor = Color.BLACK;
    private int currentThickness = 0;
    
    private List<ColorPoint> listColorPoints = new ArrayList<>();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
