/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm.tp2.exo1.exo2;

/**
 *
 * @author logan
 */
public class exo2_dessin_main_levée extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(exo2_dessin_main_levée.class.getName());

    /**
     * Creates new form exo2_dessin_main_levée
     */
    public exo2_dessin_main_levée() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_options = new javax.swing.JPanel();
        jToggleButtonBlue = new javax.swing.JToggleButton();
        jToggleButtonRed = new javax.swing.JToggleButton();
        jToggleButtonGreen = new javax.swing.JToggleButton();
        jSeparator = new javax.swing.JSeparator();
        jToggleButtonTraitFin = new javax.swing.JToggleButton();
        jToggleButtonTraitEpais = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_options.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Options"));

        jToggleButtonBlue.setBackground(new java.awt.Color(0, 0, 204));
        jPanel_options.add(jToggleButtonBlue);

        jToggleButtonRed.setBackground(new java.awt.Color(204, 0, 0));
        jPanel_options.add(jToggleButtonRed);

        jToggleButtonGreen.setBackground(new java.awt.Color(0, 204, 0));
        jPanel_options.add(jToggleButtonGreen);
        jPanel_options.add(jSeparator);

        jToggleButtonTraitFin.setText("Trait fin");
        jPanel_options.add(jToggleButtonTraitFin);

        jToggleButtonTraitEpais.setText("Trait épais");
        jPanel_options.add(jToggleButtonTraitEpais);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new exo2_dessin_main_levée().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_options;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JToggleButton jToggleButtonBlue;
    private javax.swing.JToggleButton jToggleButtonGreen;
    private javax.swing.JToggleButton jToggleButtonRed;
    private javax.swing.JToggleButton jToggleButtonTraitEpais;
    private javax.swing.JToggleButton jToggleButtonTraitFin;
    // End of variables declaration//GEN-END:variables
}
