/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm.tp2.exo1.exo2;

import java.awt.Color;

/**
 *
 * @author logan
 */
public class exo2_dessin_main_levée extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(exo2_dessin_main_levée.class.getName());

    /**
     * Creates new form exo2_dessin_main_levée
     */
    public exo2_dessin_main_levée() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColor = new javax.swing.ButtonGroup();
        buttonGroupThickness = new javax.swing.ButtonGroup();
        jPanelOptions = new javax.swing.JPanel();
        jToggleButtonBlue = new javax.swing.JToggleButton();
        jToggleButtonRed = new javax.swing.JToggleButton();
        jToggleButtonGreen = new javax.swing.JToggleButton();
        jSeparator = new javax.swing.JSeparator();
        jToggleButtonTraitFin = new javax.swing.JToggleButton();
        jToggleButtonTraitEpais = new javax.swing.JToggleButton();
        jPanelDessin = new javax.swing.JPanel();
        canva = new ihm.tp2.exo1.exo2.Canva();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Options"));

        jToggleButtonBlue.setBackground(new java.awt.Color(0, 0, 204));
        buttonGroupColor.add(jToggleButtonBlue);
        jToggleButtonBlue.addActionListener(this::jToggleButtonBlueActionPerformed);
        jPanelOptions.add(jToggleButtonBlue);

        jToggleButtonRed.setBackground(new java.awt.Color(204, 0, 0));
        buttonGroupColor.add(jToggleButtonRed);
        jToggleButtonRed.addActionListener(this::jToggleButtonRedActionPerformed);
        jPanelOptions.add(jToggleButtonRed);

        jToggleButtonGreen.setBackground(new java.awt.Color(0, 204, 0));
        buttonGroupColor.add(jToggleButtonGreen);
        jToggleButtonGreen.addActionListener(this::jToggleButtonGreenActionPerformed);
        jPanelOptions.add(jToggleButtonGreen);

        jSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanelOptions.add(jSeparator);

        buttonGroupThickness.add(jToggleButtonTraitFin);
        jToggleButtonTraitFin.setText("Trait fin");
        jToggleButtonTraitFin.addActionListener(this::jToggleButtonTraitFinActionPerformed);
        jPanelOptions.add(jToggleButtonTraitFin);

        buttonGroupThickness.add(jToggleButtonTraitEpais);
        jToggleButtonTraitEpais.setText("Trait épais");
        jToggleButtonTraitEpais.addActionListener(this::jToggleButtonTraitEpaisActionPerformed);
        jPanelOptions.add(jToggleButtonTraitEpais);

        jPanelDessin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Dessin"));

        javax.swing.GroupLayout canvaLayout = new javax.swing.GroupLayout(canva);
        canva.setLayout(canvaLayout);
        canvaLayout.setHorizontalGroup(
            canvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvaLayout.setVerticalGroup(
            canvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDessinLayout = new javax.swing.GroupLayout(jPanelDessin);
        jPanelDessin.setLayout(jPanelDessinLayout);
        jPanelDessinLayout.setHorizontalGroup(
            jPanelDessinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDessinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDessinLayout.setVerticalGroup(
            jPanelDessinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDessinLayout.createSequentialGroup()
                .addComponent(canva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDessin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDessin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonTraitFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTraitFinActionPerformed
        // On définit l'éppaisseur du trait à 4px
        canva.setCurrentThickness(4);
        
    }//GEN-LAST:event_jToggleButtonTraitFinActionPerformed

    private void jToggleButtonTraitEpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTraitEpaisActionPerformed
        // On définit l'épaisseur du trait à 8px
        canva.setCurrentThickness(8);

    }//GEN-LAST:event_jToggleButtonTraitEpaisActionPerformed

    private void jToggleButtonBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBlueActionPerformed
        // On définit la couleur des points à bleu
        canva.setCurrentColor(Color.BLUE);

    }//GEN-LAST:event_jToggleButtonBlueActionPerformed

    private void jToggleButtonRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRedActionPerformed
        // On définit la couleur des points à rouge
        canva.setCurrentColor(Color.RED);

    }//GEN-LAST:event_jToggleButtonRedActionPerformed

    private void jToggleButtonGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGreenActionPerformed
        // On définit la couleur des points à vert
        canva.setCurrentColor(Color.GREEN);

    }//GEN-LAST:event_jToggleButtonGreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new exo2_dessin_main_levée().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColor;
    private javax.swing.ButtonGroup buttonGroupThickness;
    private ihm.tp2.exo1.exo2.Canva canva;
    private javax.swing.JPanel jPanelDessin;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JToggleButton jToggleButtonBlue;
    private javax.swing.JToggleButton jToggleButtonGreen;
    private javax.swing.JToggleButton jToggleButtonRed;
    private javax.swing.JToggleButton jToggleButtonTraitEpais;
    private javax.swing.JToggleButton jToggleButtonTraitFin;
    // End of variables declaration//GEN-END:variables
}
