/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm.tp1;

import java.awt.event.KeyEvent;

/**
 *
 * @author logan
 */
public class exo1_IRE extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(exo1_IRE.class.getName());

    /**
     * Creates new form exo1_IRE
     */
    public exo1_IRE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_temperature = new javax.swing.JTextField();
        jTextField_vitesse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton_calculer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_resultat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Température (°C)");

        jTextField_temperature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_temperatureMouseClicked(evt);
            }
        });
        jTextField_temperature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_temperatureKeyPressed(evt);
            }
        });

        jTextField_vitesse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_vitesseMouseClicked(evt);
            }
        });
        jTextField_vitesse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_vitesseKeyPressed(evt);
            }
        });

        jLabel5.setText("et la vitesse du vent (km/h)");

        jButton_calculer.setText("Calculer");
        jButton_calculer.addActionListener(this::jButton_calculerActionPerformed);

        jLabel6.setText("Indice de refroidissement éolien");

        jLabel7.setText("(température ressentie (°C))");

        jTextField_resultat.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jTextField_resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jButton_calculer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_temperature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_vitesse))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_temperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_vitesse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton_calculer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean verificationType(String str){
        try {
            int valeur = Integer.parseInt(str.trim()); // trim pour éviter les espaces accidentels
            return true;
        }
        catch(NumberFormatException e){
            return false;
        }
        
    }
    
    /* On vérifie si la valeur mise en entrée est valide ou non
     @param
        int type -> 0 pour température et 1 pour vitesse
        int valeur -> valeur à vérifier
     @return
        0 -> valeur n'est pas un chiffre
        -50 -> valeur inférieur à -50 pour la température
        5 -> valeur inférieur à 5 pour la vitesse
        10 -> valeur suppérieur à 10 pour la température
        175 -> valeur suppérieur à 175 pour la vitesse
    */
    private int verificationValeur(int type, String valeur){        
        // Valeur n'est pas un chiffre -> TODO
        if(!verificationType(valeur)){
            System.out.println("[WARNING] verificationType: " + valeur + "n'est pas une valeur");
            return 0;
        }
        
        int valeur_int = Integer.parseInt(valeur);
        
        int res = 0;
        switch (type){
            case 0: // température
                // valeur inférieur à -50
                if (valeur_int < -50) res = -50;
                // valeur suppérieur à 10
                if (valeur_int > 10) res = 10;
                break;
            
            case 1: // vitesse
                // valeur inférieur à 5
                if (valeur_int < 5) res = 5;
                // valeur suppérieur à 175
                if (valeur_int > 175) res = 175;
                break;
        }
        
        return res;
 
    }
    
    private void jTextField_temperatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_temperatureMouseClicked
        // On désactive le jButton calculer
        jButton_calculer.setEnabled(false);
        jTextField_vitesse.setEnabled(false);
        
        // On supprime le contenu du jTextField_resultat
        jTextField_resultat.setText("");
    }//GEN-LAST:event_jTextField_temperatureMouseClicked

    private void jTextField_vitesseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_vitesseMouseClicked
        // On désactive le jButton calculer
        jButton_calculer.setEnabled(false);
        jTextField_temperature.setEnabled(false);

        // On supprime le contenu du jTextField_resultat
        jTextField_resultat.setText("");
    }//GEN-LAST:event_jTextField_vitesseMouseClicked

    private void jTextField_temperatureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_temperatureKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            // On réactive le bouton calculer et vitesse
            jButton_calculer.setEnabled(true);
            jTextField_vitesse.setEnabled(true);
        } 
    }//GEN-LAST:event_jTextField_temperatureKeyPressed

    private void jTextField_vitesseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_vitesseKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            // On réactive le bouton calculer et temperature
            jButton_calculer.setEnabled(true);
            jTextField_temperature.setEnabled(true);

        } 
    }//GEN-LAST:event_jTextField_vitesseKeyPressed

    private int calculIRE(int temperature, int vitesseVent){
        double result = 13.12 + 0.62215 * temperature + 
                (0.3965 * temperature - 11.37) * Math.pow(vitesseVent, 0.16);
        return (int) result;
    }
    
    
    private void jButton_calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calculerActionPerformed
        // On récupère les valeurs dans jTextField_temperature et jTextField_vitesse
        String temp = jTextField_temperature.getText();
        String vitesse = jTextField_vitesse.getText();
        int temp_verif = verificationValeur(0, temp);
        int vitesse_verif = verificationValeur(1, vitesse);
        
        int res = calculIRE(temp_verif, vitesse_verif);
        
        jTextField_resultat.setText(String.valueOf(res));
        
    }//GEN-LAST:event_jButton_calculerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new exo1_IRE().setVisible(true));        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calculer;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField_resultat;
    private javax.swing.JTextField jTextField_temperature;
    private javax.swing.JTextField jTextField_vitesse;
    // End of variables declaration//GEN-END:variables
}
