/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ihm.tp2.exo1;

import java.awt.Graphics;
import java.awt.Color;
import java.util.List;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
/**
 *
 * @author logan
 */
public class canva extends javax.swing.JPanel {

    /**
     * Creates new form canva
     */
    public canva() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
 
        // 1. Dessiner toutes les lignes définitives
        for (ColorLine line : lines) {
            g.setColor(line.color);
            g.drawLine(line.start.x, line.start.y, line.end.x, line.end.y);
        }

        // 2. Ligne temporaire gauche (noir pendant le drag)
        if (startPoint_left != null && endPoint_left != null) {
            g.setColor(Color.BLACK);
            g.drawLine(startPoint_left.x, startPoint_left.y,
                       endPoint_left.x,   endPoint_left.y);
        }

        // 3. Ligne temporaire droite (noir pendant le drag)
        if (startPoint_right != null && endPoint_right != null) {
            g.setColor(Color.BLACK);
            g.drawLine(startPoint_right.x, startPoint_right.y,
                       endPoint_right.x,   endPoint_right.y);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // On fait un clic gauche
        if(SwingUtilities.isLeftMouseButton(evt)){
            startPoint_left = evt.getPoint();
        }
        // On fait un clic droite
        if(SwingUtilities.isRightMouseButton(evt)){
            startPoint_right = evt.getPoint();
        }
        this.repaint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // On fait un clic gauche
        if(SwingUtilities.isLeftMouseButton(evt) && startPoint_left != null){
            // On rajoute à la liste des droites la nouvelle droite
            lines.add(new ColorLine(startPoint_left, evt.getPoint(), Color.RED));
            // On reset les coordonnées des points
            startPoint_left = null;
            endPoint_left = null;

        }
        // On fait un clic droite
        if(SwingUtilities.isRightMouseButton(evt) && startPoint_right != null){
            lines.add(new ColorLine(startPoint_right, evt.getPoint(), Color.BLUE));
            // On reset les coordonnées des points
            startPoint_right = null;
            endPoint_right = null;
        }
        // On oublie pas "d'update" la frame
        this.repaint();
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // On fait un clic gauche
        if(SwingUtilities.isLeftMouseButton(evt)){
            endPoint_left = evt.getPoint();
        }
        // On fait un clic droite
        if(SwingUtilities.isRightMouseButton(evt)){
            endPoint_right = evt.getPoint();
        }
        this.repaint();
    }//GEN-LAST:event_formMouseDragged

     // Liste des lignes définitives
    private List<ColorLine> lines = new ArrayList<>();

    // Points temporaires (pendant le drag)
    private Point startPoint_left  = null;
    private Point endPoint_left    = null;
    private Point startPoint_right = null;
    private Point endPoint_right   = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
